name = "permanent-link-worker"
main = "index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[vars]
MONGODB_URI = "mongodb+srv://tmpkyub4u48_db_userqgHh5C14L2PZnRYL@cluster0.ichlzod.mongodb.net/?appName=Cluster0"
BACKEND_API_SECRET = "myclonebot65432@"
